name: Industrial CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 2'

jobs:
  industrial_ci:
    name: Industrial CI (${{ matrix.env.ROS_DISTRO }}) - ${{ github.event_name }}
    strategy:
      fail-fast: false
      matrix:
        env:
          - {ROS_DISTRO: melodic, ROS_REPO: main}
          - {ROS_DISTRO: noetic, ROS_REPO: main}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{ matrix.env }}
