name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 2'

jobs:
  industrial_ci:
    name: Industrial CI - ${{ github.event_name }}
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: kinetic, ROS_REPO: main}
          - {ROS_DISTRO: melodic, ROS_REPO: main}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{ matrix.env }}
